# Generated by Django 5.2 on 2025-07-04 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cycle_min', models.IntegerField(blank=True, help_text='Durée minimale du cycle en jours', null=True)),
                ('cycle_max', models.IntegerField(blank=True, help_text='Durée maximale du cycle en jours', null=True)),
                ('rendement_min_t_ha', models.FloatField(blank=True, help_text='Rendement minimum en tonnes/hectare', null=True)),
                ('rendement_max_t_ha', models.FloatField(blank=True, help_text='Rendement maximum en tonnes/hectare', null=True)),
                ('quantite_semence_g_ha', models.FloatField(blank=True, help_text='Quantité de semences en grammes/hectare', null=True)),
                ('type_culture', models.CharField(choices=[('conventionnel', 'Conventionnel'), ('bio', 'Biologique')], default='conventionnel', max_length=20)),
                ('saisonnalite', models.CharField(blank=True, help_text='Ex: Hivernage, Saison sèche, Toute l’année', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitPhytosanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(max_length=100)),
                ('matiere_active', models.CharField(max_length=100)),
                ('type_produit', models.CharField(choices=[('fongicide', 'Fongicide'), ('insecticide', 'Insecticide'), ('bactericide', 'Bactéricide')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EtapeCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('frequence', models.CharField(max_length=50)),
                ('delai_apres_plantation', models.DurationField()),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelle.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField()),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('app', 'App')], max_length=20)),
                ('envoyee', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='farm_management.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_plantation', models.DateField()),
                ('climat', models.CharField(blank=True, max_length=100, null=True)),
                ('type_sol', models.CharField(blank=True, max_length=100, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='farm_management.farm')),
            ],
        ),
        migrations.CreateModel(
            name='CalendrierCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateField()),
                ('alerte_envoyee', models.BooleanField(default=False)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelle.etapeculture')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelle.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='Variete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('distance_plantation', models.CharField(max_length=50)),
                ('rendement_min', models.FloatField(blank=True, null=True)),
                ('rendement_max', models.FloatField(blank=True, null=True)),
                ('quantite_semence_ha', models.FloatField(blank=True, null=True)),
                ('periode_culture', models.CharField(blank=True, max_length=100, null=True)),
                ('besoins_eau', models.TextField(blank=True, null=True)),
                ('techniques_greffage', models.TextField(blank=True, null=True)),
                ('maladies_frequentes', models.TextField(blank=True, null=True)),
                ('produits_recommandes', models.TextField(blank=True, null=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varietes', to='parcelle.culture')),
            ],
        ),
        migrations.CreateModel(
            name='TraitementPhytosanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField()),
                ('type_traitement', models.CharField(max_length=100)),
                ('cible', models.CharField(max_length=100)),
                ('produit', models.CharField(max_length=100)),
                ('matiere_active', models.CharField(blank=True, max_length=100, null=True)),
                ('variete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='parcelle.variete')),
            ],
        ),
        migrations.AddField(
            model_name='parcelle',
            name='variete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelle.variete'),
        ),
        migrations.CreateModel(
            name='Fertilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField()),
                ('type_engrais', models.CharField(max_length=100)),
                ('dose_ha', models.CharField(max_length=100)),
                ('mode_application', models.CharField(blank=True, max_length=100, null=True)),
                ('variete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilisations', to='parcelle.variete')),
            ],
        ),
    ]
