# Generated by Django 5.2 on 2025-07-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='etapes',
            field=models.ManyToManyField(blank=True, to='parcelle.etapeculture'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='fertilisations',
            field=models.ManyToManyField(blank=True, to='parcelle.fertilisation'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='rendement_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='rendement_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='saison',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='semences_necessaires_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='surface_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='traitements',
            field=models.ManyToManyField(blank=True, to='parcelle.traitementphytosanitaire'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='type_culture',
            field=models.CharField(blank=True, choices=[('conventionnel', 'Conventionnel'), ('bio', 'Biologique')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='culture',
            name='cycle_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culture',
            name='cycle_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culture',
            name='quantite_semence_g_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culture',
            name='rendement_max_t_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culture',
            name='rendement_min_t_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culture',
            name='saisonnalite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
