# Generated by Django 5.2 on 2025-07-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelle', '0002_parcelle_etapes_parcelle_fertilisations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cultures/'),
        ),
        migrations.AddField(
            model_name='etapeculture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='etapes/'),
        ),
        migrations.AddField(
            model_name='fertilisation',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='fertilisations/'),
        ),
        migrations.AddField(
            model_name='produitphytosanitaire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits_phytos/'),
        ),
        migrations.AddField(
            model_name='traitementphytosanitaire',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='traitements/'),
        ),
        migrations.AddField(
            model_name='variete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='varietes/'),
        ),
    ]
