# Generated by Django 5.2 on 2025-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelle', '0003_culture_image_etapeculture_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapeculture',
            name='delai_apres_plantation',
            field=models.PositiveIntegerField(),
        ),
    ]
