# Generated by Django 5.2 on 2025-07-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelle', '0004_alter_etapeculture_delai_apres_plantation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendrierculture',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendrierculture',
            name='fertilisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelle.fertilisation'),
        ),
        migrations.AddField(
            model_name='calendrierculture',
            name='traitement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelle.traitementphytosanitaire'),
        ),
        migrations.AlterField(
            model_name='calendrierculture',
            name='etape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelle.etapeculture'),
        ),
        migrations.AlterField(
            model_name='traitementphytosanitaire',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements_utilises', to='parcelle.produitphytosanitaire'),
        ),
    ]
