# Generated by Django 5.2 on 2025-07-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelle', '0006_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
