# Generated by Django 5.2 on 2025-08-02 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0002_initial'),
        ('parcelle', '0007_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('app', 'App')], default='app', max_length=20)),
                ('envoyee', models.BooleanField(default=False)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='farm_management.farm')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
